export const data = [
  {
    id: 1,
    img: "./img/",
    drName: "James Smith",
    gender: "male",
    description: "Plastic Surgeon & Cosmetic Consultant",
    likes: 0,
    consultationFee: 100,
    city: "London",
    contact: "555.1234",
  },
  {
    id: 2,
    img: "./img/",
    drName: "Susan Johnson",
    gender: "female",
    description: "Cosmetic Surgeon",
    likes: 0,
    consultationFee: 100,
    city: "Manchester",
    contact: "555.1234",
  },
  {
    id: 3,
    img: "./img/",
    drName: "Karen Williams",
    gender: "female",
    description: "Cosmetic Dermatologist",
    likes: 0,
    consultationFee: 100,
    city: "Birmingham",
    contact: "555.1234",
  },
  {
    id: 4,
    img: "./img/",
    drName: "Jessica Jones",
    gender: "female",
    description: "Medical Aesthetician",
    likes: 0,
    consultationFee: 100,
    city: "London",
    contact: "555.1234",
  },
  {
    id: 5,
    img: "./img/",
    drName: "David Brown",
    gender: "male",
    description: "Cosmetic Dermatologist",
    likes: 0,
    consultationFee: 100,
    city: "Dublin",
    contact: "555.1234",
  },
  {
    id: 6,
    img: "./img/",
    drName: "Robert Martinez",
    gender: "male",
    description: "Plastic Surgeon ",
    likes: 0,
    consultationFee: 100,
    city: "Edinburgh",
    contact: "555.1234",
  },
];
