export const data = [
  {
    id: 1,
    img: "../imgs/clinics/st_peters.jpg",
    clinicName: "St. Peters Healthcare",
    description: "Spa for skin treatments",
    city: "London",
    contact: "555.1234",
  },
  {
    id: 2,
    img: "../imgs/clinics/marylin_spa.jpg",
    clinicName: "Marylin Spa",
    description: "Weight loss",
    city: "York",
    contact: "555.1234",
  },
  {
    id: 3,
    img: "../imgs/clinics/psychologist.jpg",
    clinicName: "Susan Mayer Clinic",
    description: "Psychologists",
    city: "Manchester",
    contact: "555.1234",
  },
  {
    id: 4,
    img: "../imgs/clinics/jones_aesthetics.jpg",
    clinicName: "Jones Aesthetics & Health",
    description: "Plastic Sugeons",
    city: "Liverpool",
    contact: "555.1234",
  },
  {
    id: 5,
    img: "../imgs/clinics/miller_wiliams.jpg",
    clinicName: "Miller and Williams Healthcare",
    description: "Cosmetic Dermatologist",
    city: "Glasgow",
    contact: "555.1234",
  },
  {
    id: 6,
    img: "../imgs/clinics/medical_aesthetics.jpg",
    clinicName: "Oxford Face",
    description: "Medical Aesthetician",
    city: "Oxford",
    contact: "555.1234",
  },
];
