export const data = [
  {
    id: 1,
    img: "../imgs/clinics/st_peters.jpg",
    clinicName: "St. Peters Healthcare",
    description: "Spa for skin treatments. Celebrate radiant skin at our luxurious spa clinic, where rejuvenation meets indulgence. Experience a harmonious blend of advanced skincare treatments and soothing therapies designed to revitalize your skin's natural glow.",
    city: "London",
    contact: "555.1234",
  },
  {
    id: 2,
    img: "../imgs/clinics/marylin_spa.jpg",
    clinicName: "Marylin Spa",
    description: "At our weight loss clinic, we're dedicated to helping you achieve your health and wellness goals. Our personalized approach combines expert medical guidance, customized meal plans, and ongoing support to help you shed unwanted pounds and embrace a healthier lifestyle.",
    city: "York",
    contact: "555.1234",
  },
  {
    id: 3,
    img: "../imgs/clinics/psychologist.jpg",
    clinicName: "Susan Mayer Clinic",
    description: "We provide compassionate and professional mental health services tailored to your individual needs. Our team of experienced psychologists offers expert counseling and therapy to help you navigate life's challenges, overcome obstacles, and achieve greater mental well-being. ",
    city: "Manchester",
    contact: "555.1234",
  },
  {
    id: 4,
    img: "../imgs/clinics/jones_aesthetics.jpg",
    clinicName: "Jones Aesthetics & Health",
    description: "Welcome to Jones Aesthetics & Health, where we specialize in transforming dreams into reality. Our expert team of plastic surgeons combines artistry with advanced medical techniques to enhance your natural beauty and boost your confidence. ",
    city: "Liverpool",
    contact: "555.1234",
  },
  {
    id: 5,
    img: "../imgs/clinics/miller_wiliams.jpg",
    clinicName: "Miller and Williams Healthcare",
    description: "Our team of skilled Cosmetic Dermatologists is dedicated to enhancing your natural beauty and restoring your confidence. From advanced skincare treatments to personalized aesthetic procedures, we offer comprehensive solutions tailored to your unique needs. ",
    city: "Glasgow",
    contact: "555.1234",
  },
  {
    id: 6,
    img: "../imgs/clinics/medical_aesthetics.jpg",
    clinicName: "Oxford Face",
    description: "Discover the art of skincare at our clinic, where our experienced Medical Aesthetician specializes in advanced treatments tailored to rejuvenate and enhance your natural beauty. ",
    city: "Oxford",
    contact: "555.1234",
  },
];
